version: '3.8'
services:
  api:
    build: .
    container_name: osm-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - OVERPASS_URL=https://overpass-api.de/api/interpreter
      - POSTGRES_HOST=db
      - POSTGRES_DB=osm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgis/postgis:15-3.3
    container_name: osm-postgis
    restart: always
    environment:
      - POSTGRES_DB=osm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
